# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Configure build for amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Build
        shell: pwsh
        run: |
          git clone https://github.com/protocolbuffers/protobuf.git
          cd protobuf
          git submodule update --init --recursive
          New-Item -ItemType Directory -Force -Path "C:\protobuf_install"
          New-Item -ItemType Directory -Force -Name "build"; Set-Location -Path "build"
          cmake .. -G "Visual Studio 17 2022" `
            -DCMAKE_CXX_STANDARD=20 `
            -DCMAKE_CONFIGURATION_TYPES="Release" `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_INSTALL_PREFIX="C:\protobuf_install" `
            -DBUILD_TESTING=OFF `
            -Dprotobuf_BUILD_TESTS=OFF
          msbuild protobuf.sln /p:Configuration=Release /p:Platform=x64
          cmake --install .
